<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ./public/basic.gltf
-->

<script>
  import { T } from "@threlte/core";
  import { useGltf } from "@threlte/extras";
    import { randInt } from "three/src/math/MathUtils.js";

  let { fallback, error, children, ref = $bindable(), ...props } = $props();

  const nodeNames = [
    "Shard_1",
    "Shard_2",
    "Shard_3",
    "Shard_4",
    "Shard_5",
    "Shard_6",
    "Shard_7",
    "Shard_8",
  ]
  const nodeSmallNames = [
    "Shard_1",
    "Shard_2",
    "Shard_3",
    "Shard_4",
    "Shard_5",
    "Shard_6",
    "Shard_7",
    "Shard_8",
  ]
  const gltf = useGltf("/shards.gltf");
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes[nodeNames[randInt(0, nodeNames.length-1)]].geometry}
      material={gltf.nodes[nodeNames[randInt(0, nodeNames.length-1)]].material}
      rotation={[Math.PI / 2, 0, 0]}
      scale={[16.25, 0.95, 9.25]}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
